export const SUBSCRIPTION_CLICK_ANON = 'SUBSCRIPTION_CLICK_ANON';
export const SUBSCRIPTION_CLICK_USER = 'SUBSCRIPTION_CLICK_USER';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_URL = 'UPLOAD_URL';
export const UPLOAD_YOUTUBE = 'UPLOAD_YOUTUBE';
export const USER_CHAT = 'USER_CHAT';
export const DEMO_CLICKED = 'DEMO_CLICKED';
export const LOGIN_CLICK = 'LOGIN_CLICK';
export const FLAST_QUERY = 'FLAST_QUERY';

// export const CREATE_USER = 'CREATE_USER';