name: Build and Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into server and run build
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            source ~/.nvm/nvm.sh
            nvm use 18
            cd /var/www/vigilant-octo-invention
            git pull || { echo "git pull failed"; exit 1; }
            npm ci || { echo "npm ci failed"; exit 1; }
            npm run build || { echo "npm run build failed"; exit 1; }
            pm2 restart docXpert || { echo "pm2 restart failed"; exit 1; }

      - name: Notify Deployment Success
        if: success() 
        run: echo "Deployment to server was successful!"

      - name: Notify Deployment Failure
        if: failure() 
        run: echo "Deployment to server failed. Check the workflow logs for details."
