name: Build and Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into server and run build
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            source ~/.nvm/nvm.sh
            nvm use 18
            cd /var/www/vigilant-oto-invention
            git pull 
            npm ci 
            npm run build 
            pm2 restart docXpert || { echo "pm2 restart failed"; exit 1; }

      - name: Notify Deployment Success
        if: success() 
        run: echo "Deployment to server was successful!"

      - name: Notify Deployment Failure
        if: failure() 
        run: echo "Deployment to server failed. Check the workflow logs for details."
