name: Deploy Next.js to DigitalOcean

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Service Key
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_KEY }}' > servicekey.json
           echo 'JSON content: $secrets.FIREBASE_SERVICE_KEY'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build 

      - name: Upload files to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: ./.next/ 
          target: / 

      # - name: SSH into Droplet and restart server
      #   run: |
      #     ssh -i ${{ secrets.DROPLET_SSH_KEY }} ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} "cd / && pm2 restart docXpert" 
