name: build and deploy to server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: SSH into server and run commands
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "cd /var/www/vigilant-octo-invention && git pull && npm install && npm run build && pm2 restart docXpert"
